import jsPDF from 'jspdf';
import * as XLSX from 'xlsx';
import { Calculation } from '@/store/calculationStore';

export const exportToPDF = (calculation: Calculation) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.text('Soneras Engineering Report', 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.text(`Product: ${calculation.productName}`, 20, 40);
  doc.text(`Engineer: ${calculation.engineer}`, 20, 50);
  doc.text(`Date: ${new Date(calculation.timestamp).toLocaleDateString()}`, 20, 60);
  
  // Input Data Section
  doc.setFontSize(14);
  doc.text('Input Parameters', 20, 80);
  doc.setFontSize(10);
  
  let yPos = 90;
  doc.text(`Hot Fluid Temperature In: ${calculation.input.hotFluidTempIn} °C`, 20, yPos);
  yPos += 10;
  doc.text(`Hot Fluid Temperature Out: ${calculation.input.hotFluidTempOut} °C`, 20, yPos);
  yPos += 10;
  doc.text(`Cold Fluid Temperature In: ${calculation.input.coldFluidTempIn} °C`, 20, yPos);
  yPos += 10;
  doc.text(`Cold Fluid Temperature Out: ${calculation.input.coldFluidTempOut} °C`, 20, yPos);
  
  // Results Section
  yPos += 20;
  doc.setFontSize(14);
  doc.text('Calculation Results', 20, yPos);
  doc.setFontSize(10);
  
  yPos += 10;
  doc.text(`Reynolds Number (Hot): ${calculation.results.reynoldsHot.toFixed(2)}`, 20, yPos);
  yPos += 10;
  doc.text(`Reynolds Number (Cold): ${calculation.results.reynoldsCold.toFixed(2)}`, 20, yPos);
  yPos += 10;
  doc.text(`Effectiveness: ${(calculation.results.effectiveness * 100).toFixed(2)}%`, 20, yPos);
  yPos += 10;
  doc.text(`Heat Transfer Rate: ${calculation.results.heatTransferRate.toFixed(2)} W`, 20, yPos);
  yPos += 10;
  doc.text(`Configuration: ${calculation.results.configuration}`, 20, yPos);
  yPos += 10;
  doc.text(`Flow Regime: ${calculation.results.flowRegime}`, 20, yPos);
  
  // Footer
  doc.setFontSize(8);
  doc.text('Generated by Soneras Radiator Engineering Suite', 105, 280, { align: 'center' });
  
  doc.save(`soneras_report_${calculation.id}.pdf`);
};

export const exportToExcel = (calculation: Calculation) => {
  const workbook = XLSX.utils.book_new();
  
  // Input Data Sheet
  const inputData = [
    ['Parameter', 'Value', 'Unit'],
    ['Hot Fluid Temperature In', calculation.input.hotFluidTempIn, '°C'],
    ['Hot Fluid Temperature Out', calculation.input.hotFluidTempOut, '°C'],
    ['Cold Fluid Temperature In', calculation.input.coldFluidTempIn, '°C'],
    ['Cold Fluid Temperature Out', calculation.input.coldFluidTempOut, '°C'],
    ['Hot Fluid Mass Flow', calculation.input.hotFluidMassFlow, 'kg/s'],
    ['Cold Fluid Mass Flow', calculation.input.coldFluidMassFlow, 'kg/s'],
    ['Tube External Diameter', calculation.input.tubeExtDiameter, 'm'],
    ['Tube Internal Diameter', calculation.input.tubeIntDiameter, 'm'],
    ['Tube Length', calculation.input.tubeLength, 'm'],
    ['Number of Tubes', calculation.input.numberOfTubes, ''],
  ];
  
  const inputSheet = XLSX.utils.aoa_to_sheet(inputData);
  XLSX.utils.book_append_sheet(workbook, inputSheet, 'Input Data');
  
  // Results Sheet
  const resultsData = [
    ['Parameter', 'Value', 'Unit'],
    ['Reynolds Number (Hot)', calculation.results.reynoldsHot.toFixed(4), ''],
    ['Reynolds Number (Cold)', calculation.results.reynoldsCold.toFixed(4), ''],
    ['Prandtl Number (Hot)', calculation.results.prandtlHot.toFixed(4), ''],
    ['Prandtl Number (Cold)', calculation.results.prandtlCold.toFixed(4), ''],
    ['Nusselt Number (Hot)', calculation.results.nusseltHot.toFixed(4), ''],
    ['Nusselt Number (Cold)', calculation.results.nusseltCold.toFixed(4), ''],
    ['Effectiveness', (calculation.results.effectiveness * 100).toFixed(2), '%'],
    ['NTU', calculation.results.ntu.toFixed(4), ''],
    ['Heat Transfer Rate', calculation.results.heatTransferRate.toFixed(2), 'W'],
    ['Pressure Drop (Hot)', calculation.results.pressureDropHot.toFixed(2), 'Pa'],
    ['Pressure Drop (Cold)', calculation.results.pressureDropCold.toFixed(2), 'Pa'],
    ['Configuration', calculation.results.configuration, ''],
    ['Flow Regime', calculation.results.flowRegime, ''],
  ];
  
  const resultsSheet = XLSX.utils.aoa_to_sheet(resultsData);
  XLSX.utils.book_append_sheet(workbook, resultsSheet, 'Results');
  
  XLSX.writeFile(workbook, `soneras_calculation_${calculation.id}.xlsx`);
};

export const exportToCSV = (calculations: Calculation[]) => {
  const csvData = calculations.map(calc => ({
    ID: calc.id,
    Product: calc.productName,
    Engineer: calc.engineer,
    Date: new Date(calc.timestamp).toLocaleDateString(),
    'Reynolds Hot': calc.results.reynoldsHot.toFixed(2),
    'Reynolds Cold': calc.results.reynoldsCold.toFixed(2),
    'Effectiveness (%)': (calc.results.effectiveness * 100).toFixed(2),
    'Heat Transfer (W)': calc.results.heatTransferRate.toFixed(2),
    Configuration: calc.results.configuration,
  }));
  
  const worksheet = XLSX.utils.json_to_sheet(csvData);
  const csvOutput = XLSX.utils.sheet_to_csv(worksheet);
  
  const blob = new Blob([csvOutput], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `soneras_calculations_${Date.now()}.csv`;
  link.click();
};
